/** Declaration file generated by dts-gen */

import { Adapter} from 'escpos'

export = WebUSB;

declare class WebUSB implements Adapter {
    constructor(usbDevice?: USBDevice, configurationValue?: number, interfaceNumber?: number, endpointNumber?: number);

    open(callback?: (error?: any) => void): Adapter;

    write(data: Buffer, callback: (error?: any) => void): Adapter;

}

